### PR TITLE
implemented conversion from hessian_pos to hessian,

### PR DESCRIPTION
**Pull request by cortner**
+ finite difference test for hessian and a few little bug fixes;

but the hessian test still fails for now. not sure what has gone wrong

### CODE REVIEW

**Comment by git4lei** [comment]
Thanks, I have merged your update, and run the fdtest, will see why it fails.

**Comment by git4lei** [comment]
fdtest works for 
at = bulk("Cu", cubic=true)
but fails for
at = bulk("Cu", cubic=true)*2
I am trying to debug it, can I show the index of atoms or bonds in JuLIP.Visualise.show(at)?

**Comment by cortner** [comment]
Yes, I can reproduce this. Very interesting. The same happens if I turn on PBCs. 

> I am trying to debug it, can I show the index of atoms or bonds in JuLIP.Visualise.show(at)?

no - sorry.

**Comment by cortner** [comment]
You could try to create a finite-difference test for the block-matrix version of the hessian. Maybe one can see more there?

**Pull request merged**
